import { create } from 'zustand'

export const useAppStore = create((set) => ({
  language: 'en',
  darkMode: true,
  setLanguage: (lang) => set({ language: lang }),
  toggleDark: () => set((state) => ({ darkMode: !state.darkMode })),
}))

export const languages = [
  { code: 'en',       native: 'English',    full: 'English' },
  { code: 'hi',       native: 'हिंदी',      full: 'Hindi' },
  { code: 'hinglish', native: 'Hinglish',   full: 'Hinglish' },
  { code: 'mr',       native: 'मराठी',      full: 'Marathi' },
  { code: 'gu',       native: 'ગુજરાતી',    full: 'Gujarati' },
  { code: 'ta',       native: 'தமிழ்',      full: 'Tamil' },
  { code: 'te',       native: 'తెలుగు',     full: 'Telugu' },
  { code: 'kn',       native: 'ಕನ್ನಡ',      full: 'Kannada' },
  { code: 'ml',       native: 'മലയാളം',     full: 'Malayalam' },
  { code: 'pa',       native: 'ਪੰਜਾਬੀ',     full: 'Punjabi' },
  { code: 'bn',       native: 'বাংলা',      full: 'Bengali' },
  { code: 'as',       native: 'অসমীয়া',    full: 'Assamese' },
  { code: 'or',       native: 'ଓଡ଼ିଆ',      full: 'Odia' },
  { code: 'ur',       native: 'اردو',       full: 'Urdu' },
]

export const translations = {
  en: {
    tagline: "India's first AI-powered government hospital navigator",
    hero1: "Right Treatment.", hero2: "Right Place.",
    subtitle: "Find government hospitals in your district — free departments, OPD timings, and Ayushman coverage — all in one place.",
    placeholder: "Search hospital name...",
    allDistricts: "All Districts (UP)", search: "Search →",
    stats1: "Govt Hospitals", stats2: "Departments", stats3: "Free OPD", stats4: "Districts",
    featTitle: "What does Arogya.ai do?", featSub: "Everything you need — on one platform",
    howTitle: "Find treatment in 3 steps",
    ctaTitle: "Ready to find your hospital?",
    ctaSub: "70% of Indians depend on government hospitals. Arogya.ai is built for them.",
    ctaBtn: "Find Hospital →", footerSub: "Right treatment, right place, right time",
    step1: "Search", step1d: "Type your symptom or district in the search bar",
    step2: "Choose", step2d: "Pick the nearest hospital — see free departments and timings",
    step3: "Go", step3d: "Get directions, check OPD requirements, get treated",
  },
  hi: {
    tagline: "भारत का पहला AI-powered सरकारी अस्पताल navigator",
    hero1: "सही इलाज।", hero2: "सही जगह।",
    subtitle: "अपने जिले के सरकारी अस्पताल खोजें — मुफ्त विभाग, OPD समय, आयुष्मान कवरेज।",
    placeholder: "अस्पताल का नाम लिखें...",
    allDistricts: "सभी जिले (UP)", search: "खोजें →",
    stats1: "सरकारी अस्पताल", stats2: "विभाग", stats3: "मुफ्त OPD", stats4: "जिले",
    featTitle: "Arogya.ai क्या करता है?", featSub: "सब कुछ एक प्लेटफॉर्म पर",
    howTitle: "3 steps में इलाज खोजें",
    ctaTitle: "अपना अस्पताल खोजने के लिए तैयार हैं?",
    ctaSub: "भारत के 70% लोग सरकारी अस्पतालों पर निर्भर हैं।",
    ctaBtn: "अस्पताल खोजें →", footerSub: "सही इलाज, सही जगह, सही वक्त",
    step1: "खोजें", step1d: "अपना लक्षण या जिला टाइप करें",
    step2: "चुनें", step2d: "नजदीकी अस्पताल चुनें — मुफ्त विभाग देखें",
    step3: "जाएं", step3d: "दिशा-निर्देश लें, OPD कार्ड बनवाएं",
  },
  hinglish: {
    tagline: "India ka pehla AI-powered sarkari hospital navigator",
    hero1: "Sahi Ilaaj.", hero2: "Sahi Jagah.",
    subtitle: "Apne district ke sarkari hospitals dhundho — free departments, OPD timings, aur Ayushman coverage.",
    placeholder: "Hospital ka naam likhein...",
    allDistricts: "Sabhi Districts (UP)", search: "Dhundho →",
    stats1: "Sarkari Hospitals", stats2: "Departments", stats3: "Free OPD", stats4: "Districts",
    featTitle: "Arogya.ai kya karta hai?", featSub: "Sab kuch ek platform pe",
    howTitle: "3 steps mein ilaaj dhundho",
    ctaTitle: "Ready to find your hospital?",
    ctaSub: "India ke 70% log sarkari hospitals pe depend karte hain.",
    ctaBtn: "Hospital Dhundho →", footerSub: "Sahi ilaaj, sahi jagah, sahi waqt",
    step1: "Dhundho", step1d: "Apna symptom ya district type karein",
    step2: "Chunein", step2d: "Nazdiki hospital chunein — free departments dekhein",
    step3: "Jaiye", step3d: "Directions lein, OPD card banwayein",
  },
  mr: {
    tagline: "भारताचा पहिला AI-powered सरकारी रुग्णालय navigator",
    hero1: "योग्य उपचार.", hero2: "योग्य ठिकाण.",
    subtitle: "तुमच्या जिल्ह्यातील सरकारी रुग्णालये शोधा — मोफत विभाग, OPD वेळ.",
    placeholder: "लक्षण किंवा रुग्णालयाचे नाव टाइप करा...",
    allDistricts: "सर्व जिल्हे", search: "शोधा →",
    stats1: "सरकारी रुग्णालये", stats2: "विभाग", stats3: "मोफत OPD", stats4: "जिल्हे",
    featTitle: "Arogya.ai काय करते?", featSub: "सर्वकाही एका प्लॅटफॉर्मवर",
    howTitle: "3 steps मध्ये उपचार शोधा",
    ctaTitle: "तुमचे रुग्णालय शोधण्यास तयार आहात?",
    ctaSub: "भारतातील 70% लोक सरकारी रुग्णालयांवर अवलंबून आहेत.",
    ctaBtn: "रुग्णालय शोधा →", footerSub: "योग्य उपचार, योग्य ठिकाण, योग्य वेळ",
    step1: "शोधा", step1d: "तुमचे लक्षण किंवा जिल्हा टाइप करा",
    step2: "निवडा", step2d: "जवळचे रुग्णालय निवडा",
    step3: "जा", step3d: "दिशा मिळवा, OPD कार्ड बनवा",
  },
  gu: {
    tagline: "ભારતનું પ્રથમ AI-powered સરકારી હોસ્પિટલ navigator",
    hero1: "યોગ્ય સારવાર.", hero2: "યોગ્ય જગ્યા.",
    subtitle: "તમારા જિલ્લાની સરકારી હોસ્પિટલ શોધો — મફત વિભાગ, OPD સમય.",
    placeholder: "લક્ષણ અથવા હોસ્પિટલનું નામ ટાઇપ કરો...",
    allDistricts: "બધા જિલ્લા", search: "શોધો →",
    stats1: "સરકારી હોસ્પિટલ", stats2: "વિભાગ", stats3: "મફત OPD", stats4: "જિલ્લા",
    featTitle: "Arogya.ai શું કરે છે?", featSub: "બધું એક પ્લેટફોર્મ પર",
    howTitle: "3 steps માં સારવાર શોધો",
    ctaTitle: "તમારી હોસ્પિટલ શોધવા તૈયાર છો?",
    ctaSub: "ભારતના 70% લોકો સરકારી હોસ્પિટલ પર આધાર રાખે છે.",
    ctaBtn: "હોસ્પિટલ શોધો →", footerSub: "યોગ્ય સારવાર, યોગ્ય જગ્યા, યોગ્ય સમય",
    step1: "શોધો", step1d: "તમારું લક્ષણ અથવા જિલ્લો ટાઇપ કરો",
    step2: "પસંદ કરો", step2d: "નજીકની હોસ્પિટલ પસંદ કરો",
    step3: "જાઓ", step3d: "દિશા મેળવો, OPD કાર્ડ બનાવો",
  },
  ta: {
    tagline: "இந்தியாவின் முதல் AI-powered அரசு மருத்துவமனை navigator",
    hero1: "சரியான சிகிச்சை.", hero2: "சரியான இடம்.",
    subtitle: "உங்கள் மாவட்டத்தில் அரசு மருத்துவமனைகளை கண்டறியுங்கள் — இலவச பிரிவுகள், OPD நேரங்கள்.",
    placeholder: "அறிகுறி அல்லது மருத்துவமனை பெயரை தேடுங்கள்...",
    allDistricts: "அனைத்து மாவட்டங்கள்", search: "தேடு →",
    stats1: "அரசு மருத்துவமனைகள்", stats2: "பிரிவுகள்", stats3: "இலவச OPD", stats4: "மாவட்டங்கள்",
    featTitle: "Arogya.ai என்ன செய்கிறது?", featSub: "எல்லாமே ஒரே தளத்தில்",
    howTitle: "3 படிகளில் சிகிச்சை கண்டறியுங்கள்",
    ctaTitle: "உங்கள் மருத்துவமனையை கண்டறிய தயாரா?",
    ctaSub: "இந்தியாவின் 70% மக்கள் அரசு மருத்துவமனைகளை நம்பியுள்ளனர்.",
    ctaBtn: "மருத்துவமனை தேடு →", footerSub: "சரியான சிகிச்சை, சரியான இடம், சரியான நேரம்",
    step1: "தேடு", step1d: "உங்கள் அறிகுறி அல்லது மாவட்டத்தை தட்டச்சு செய்யுங்கள்",
    step2: "தேர்வு செய்", step2d: "அருகிலுள்ள மருத்துவமனையை தேர்வு செய்யுங்கள்",
    step3: "செல்", step3d: "திசைகளைப் பெறுங்கள், OPD அட்டை பெறுங்கள்",
  },
  te: {
    tagline: "భారతదేశపు మొదటి AI-powered ప్రభుత్వ ఆసుపత్రి navigator",
    hero1: "సరైన చికిత్స.", hero2: "సరైన స్థలం.",
    subtitle: "మీ జిల్లాలో ప్రభుత్వ ఆసుపత్రులు కనుగొనండి — ఉచిత విభాగాలు, OPD సమయాలు.",
    placeholder: "లక్షణం లేదా ఆసుపత్రి పేరు వెతకండి...",
    allDistricts: "అన్ని జిల్లాలు", search: "వెతుకు →",
    stats1: "ప్రభుత్వ ఆసుపత్రులు", stats2: "విభాగాలు", stats3: "ఉచిత OPD", stats4: "జిల్లాలు",
    featTitle: "Arogya.ai ఏమి చేస్తుంది?", featSub: "అన్నీ ఒక్క వేదికపై",
    howTitle: "3 దశల్లో చికిత్స కనుగొనండి",
    ctaTitle: "మీ ఆసుపత్రి కనుగొనడానికి సిద్ధంగా ఉన్నారా?",
    ctaSub: "భారతదేశంలో 70% ప్రజలు ప్రభుత్వ ఆసుపత్రులపై ఆధారపడతారు.",
    ctaBtn: "ఆసుపత్రి వెతుకు →", footerSub: "సరైన చికిత్స, సరైన స్థలం, సరైన సమయం",
    step1: "వెతుకు", step1d: "మీ లక్షణం లేదా జిల్లా టైప్ చేయండి",
    step2: "ఎంచుకో", step2d: "సమీప ఆసుపత్రి ఎంచుకోండి",
    step3: "వెళ్ళు", step3d: "దిశలు పొందండి, OPD కార్డు తీసుకోండి",
  },
  kn: {
    tagline: "ಭಾರತದ ಮೊದಲ AI-powered ಸರ್ಕಾರಿ ಆಸ್ಪತ್ರೆ navigator",
    hero1: "ಸರಿಯಾದ ಚಿಕಿತ್ಸೆ.", hero2: "ಸರಿಯಾದ ಸ್ಥಳ.",
    subtitle: "ನಿಮ್ಮ ಜಿಲ್ಲೆಯ ಸರ್ಕಾರಿ ಆಸ್ಪತ್ರೆಗಳನ್ನು ಹುಡುಕಿ — ಉಚಿತ ವಿಭಾಗಗಳು, OPD ಸಮಯಗಳು.",
    placeholder: "ರೋಗಲಕ್ಷಣ ಅಥವಾ ಆಸ್ಪತ್ರೆಯ ಹೆಸರು ಹುಡುಕಿ...",
    allDistricts: "ಎಲ್ಲಾ ಜಿಲ್ಲೆಗಳು", search: "ಹುಡುಕು →",
    stats1: "ಸರ್ಕಾರಿ ಆಸ್ಪತ್ರೆಗಳು", stats2: "ವಿಭಾಗಗಳು", stats3: "ಉಚಿತ OPD", stats4: "ಜಿಲ್ಲೆಗಳು",
    featTitle: "Arogya.ai ಏನು ಮಾಡುತ್ತದೆ?", featSub: "ಎಲ್ಲವೂ ಒಂದೇ ವೇದಿಕೆಯಲ್ಲಿ",
    howTitle: "3 ಹಂತಗಳಲ್ಲಿ ಚಿಕಿತ್ಸೆ ಹುಡುಕಿ",
    ctaTitle: "ನಿಮ್ಮ ಆಸ್ಪತ್ರೆ ಹುಡುಕಲು ಸಿದ್ಧರಾಗಿದ್ದೀರಾ?",
    ctaSub: "ಭಾರತದ 70% ಜನರು ಸರ್ಕಾರಿ ಆಸ್ಪತ್ರೆಗಳನ್ನು ಅವಲಂಬಿಸಿದ್ದಾರೆ.",
    ctaBtn: "ಆಸ್ಪತ್ರೆ ಹುಡುಕಿ →", footerSub: "ಸರಿಯಾದ ಚಿಕಿತ್ಸೆ, ಸರಿಯಾದ ಸ್ಥಳ, ಸರಿಯಾದ ಸಮಯ",
    step1: "ಹುಡುಕಿ", step1d: "ನಿಮ್ಮ ರೋಗಲಕ್ಷಣ ಅಥವಾ ಜಿಲ್ಲೆ ಟೈಪ್ ಮಾಡಿ",
    step2: "ಆಯ್ಕೆ ಮಾಡಿ", step2d: "ಹತ್ತಿರದ ಆಸ್ಪತ್ರೆ ಆಯ್ಕೆ ಮಾಡಿ",
    step3: "ಹೋಗಿ", step3d: "ದಿಕ್ಕುಗಳನ್ನು ಪಡೆಯಿರಿ, OPD ಕಾರ್ಡ್ ಪಡೆಯಿರಿ",
  },
  ml: {
    tagline: "ഇന്ത്യയിലെ ആദ്യത്തെ AI-powered സർക്കാർ ആശുപത്രി navigator",
    hero1: "ശരിയായ ചികിത്സ.", hero2: "ശരിയായ സ്ഥലം.",
    subtitle: "നിങ്ങളുടെ ജില്ലയിലെ സർക്കാർ ആശുപത്രികൾ കണ്ടെത്തുക — സൗജന്യ വകുപ്പുകൾ, OPD സമയങ്ങൾ.",
    placeholder: "രോഗലക്ഷണം അല്ലെങ്കിൽ ആശുപത്രി പേര് തിരയുക...",
    allDistricts: "എല്ലാ ജില്ലകളും", search: "തിരയുക →",
    stats1: "സർക്കാർ ആശുപത്രികൾ", stats2: "വകുപ്പുകൾ", stats3: "സൗജന്യ OPD", stats4: "ജില്ലകൾ",
    featTitle: "Arogya.ai എന്ത് ചെയ്യുന്നു?", featSub: "എല്ലാം ഒരു പ്ലാറ്റ്ഫോമിൽ",
    howTitle: "3 ഘട്ടങ്ങളിൽ ചികിത്സ കണ്ടെത്തുക",
    ctaTitle: "നിങ്ങളുടെ ആശുപത്രി കണ്ടെത്താൻ തയ്യാറാണോ?",
    ctaSub: "ഇന്ത്യയിലെ 70% ആളുകൾ സർക്കാർ ആശുപത്രികളെ ആശ്രയിക്കുന്നു.",
    ctaBtn: "ആശുപത്രി തിരയുക →", footerSub: "ശരിയായ ചികിത്സ, ശരിയായ സ്ഥലം, ശരിയായ സമയം",
    step1: "തിരയുക", step1d: "നിങ്ങളുടെ രോഗലക്ഷണം അല്ലെങ്കിൽ ജില്ല ടൈപ്പ് ചെയ്യുക",
    step2: "തിരഞ്ഞെടുക്കുക", step2d: "അടുത്തുള്ള ആശുപത്രി തിരഞ്ഞെടുക്കുക",
    step3: "പോകുക", step3d: "ദിശകൾ നേടുക, OPD കാർഡ് നേടുക",
  },
  pa: {
    tagline: "ਭਾਰਤ ਦਾ ਪਹਿਲਾ AI-powered ਸਰਕਾਰੀ ਹਸਪਤਾਲ navigator",
    hero1: "ਸਹੀ ਇਲਾਜ.", hero2: "ਸਹੀ ਜਗ੍ਹਾ.",
    subtitle: "ਆਪਣੇ ਜ਼ਿਲ੍ਹੇ ਦੇ ਸਰਕਾਰੀ ਹਸਪਤਾਲ ਲੱਭੋ — ਮੁਫ਼ਤ ਵਿਭਾਗ, OPD ਸਮਾਂ.",
    placeholder: "ਲੱਛਣ ਜਾਂ ਹਸਪਤਾਲ ਦਾ ਨਾਮ ਲਿਖੋ...",
    allDistricts: "ਸਾਰੇ ਜ਼ਿਲ੍ਹੇ", search: "ਲੱਭੋ →",
    stats1: "ਸਰਕਾਰੀ ਹਸਪਤਾਲ", stats2: "ਵਿਭਾਗ", stats3: "ਮੁਫ਼ਤ OPD", stats4: "ਜ਼ਿਲ੍ਹੇ",
    featTitle: "Arogya.ai ਕੀ ਕਰਦਾ ਹੈ?", featSub: "ਸਭ ਕੁਝ ਇੱਕ ਪਲੇਟਫਾਰਮ 'ਤੇ",
    howTitle: "3 ਕਦਮਾਂ ਵਿੱਚ ਇਲਾਜ ਲੱਭੋ",
    ctaTitle: "ਆਪਣਾ ਹਸਪਤਾਲ ਲੱਭਣ ਲਈ ਤਿਆਰ ਹੋ?",
    ctaSub: "ਭਾਰਤ ਦੇ 70% ਲੋਕ ਸਰਕਾਰੀ ਹਸਪਤਾਲਾਂ 'ਤੇ ਨਿਰਭਰ ਕਰਦੇ ਹਨ.",
    ctaBtn: "ਹਸਪਤਾਲ ਲੱਭੋ →", footerSub: "ਸਹੀ ਇਲਾਜ, ਸਹੀ ਜਗ੍ਹਾ, ਸਹੀ ਸਮਾਂ",
    step1: "ਲੱਭੋ", step1d: "ਆਪਣਾ ਲੱਛਣ ਜਾਂ ਜ਼ਿਲ੍ਹਾ ਟਾਈਪ ਕਰੋ",
    step2: "ਚੁਣੋ", step2d: "ਨੇੜੇ ਦਾ ਹਸਪਤਾਲ ਚੁਣੋ",
    step3: "ਜਾਓ", step3d: "ਦਿਸ਼ਾ ਲਓ, OPD ਕਾਰਡ ਬਣਵਾਓ",
  },
  bn: {
    tagline: "ভারতের প্রথম AI-powered সরকারি হাসপাতাল navigator",
    hero1: "সঠিক চিকিৎসা.", hero2: "সঠিক জায়গা.",
    subtitle: "আপনার জেলায় সরকারি হাসপাতাল খুঁজুন — বিনামূল্যে বিভাগ, OPD সময়.",
    placeholder: "লক্ষণ বা হাসপাতালের নাম খুঁজুন...",
    allDistricts: "সব জেলা", search: "খুঁজুন →",
    stats1: "সরকারি হাসপাতাল", stats2: "বিভাগ", stats3: "বিনামূল্যে OPD", stats4: "জেলা",
    featTitle: "Arogya.ai কী করে?", featSub: "সব কিছু এক প্ল্যাটফর্মে",
    howTitle: "৩ ধাপে চিকিৎসা খুঁজুন",
    ctaTitle: "আপনার হাসপাতাল খুঁজতে প্রস্তুত?",
    ctaSub: "ভারতের ৭০% মানুষ সরকারি হাসপাতালের উপর নির্ভর করে.",
    ctaBtn: "হাসপাতাল খুঁজুন →", footerSub: "সঠিক চিকিৎসা, সঠিক জায়গা, সঠিক সময়",
    step1: "খুঁজুন", step1d: "আপনার লক্ষণ বা জেলা টাইপ করুন",
    step2: "বেছে নিন", step2d: "কাছের হাসপাতাল বেছে নিন",
    step3: "যান", step3d: "দিকনির্দেশনা পান, OPD কার্ড নিন",
  },
  as: {
    tagline: "ভাৰতৰ প্ৰথম AI-powered চৰকাৰী হাস্পতাল navigator",
    hero1: "সঠিক চিকিৎসা.", hero2: "সঠিক ঠাই.",
    subtitle: "আপোনাৰ জিলাত চৰকাৰী হাস্পতাল বিচাৰক — বিনামূলীয়া বিভাগ, OPD সময়.",
    placeholder: "লক্ষণ বা হাস্পতালৰ নাম বিচাৰক...",
    allDistricts: "সকলো জিলা", search: "বিচাৰক →",
    stats1: "চৰকাৰী হাস্পতাল", stats2: "বিভাগ", stats3: "বিনামূলীয়া OPD", stats4: "জিলা",
    featTitle: "Arogya.ai কি কৰে?", featSub: "সকলো এটা প্লেটফৰ্মত",
    howTitle: "৩ পদক্ষেপত চিকিৎসা বিচাৰক",
    ctaTitle: "আপোনাৰ হাস্পতাল বিচাৰিবলৈ সাজু?",
    ctaSub: "ভাৰতৰ ৭০% লোক চৰকাৰী হাস্পতালৰ ওপৰত নিৰ্ভৰ কৰে.",
    ctaBtn: "হাস্পতাল বিচাৰক →", footerSub: "সঠিক চিকিৎসা, সঠিক ঠাই, সঠিক সময়",
    step1: "বিচাৰক", step1d: "আপোনাৰ লক্ষণ বা জিলা টাইপ কৰক",
    step2: "বাছক", step2d: "ওচৰৰ হাস্পতাল বাছক",
    step3: "যাওক", step3d: "দিকনিৰ্দেশনা লওক",
  },
  or: {
    tagline: "ଭାରତର ପ୍ରଥମ AI-powered ସରକାରୀ ଡାକ୍ତରଖାନା navigator",
    hero1: "ସଠିକ ଚିକିତ୍ସା.", hero2: "ସଠିକ ଜାଗା.",
    subtitle: "ଆପଣଙ୍କ ଜିଲ୍ଲାରେ ସରକାରୀ ଡାକ୍ତରଖାନା ଖୋଜନ୍ତୁ — ମୁଫ୍ତ ବିଭାଗ, OPD ସମୟ.",
    placeholder: "ଲକ୍ଷଣ ବା ଡାକ୍ତରଖାନା ନାମ ଖୋଜନ୍ତୁ...",
    allDistricts: "ସବୁ ଜିଲ୍ଲା", search: "ଖୋଜ →",
    stats1: "ସରକାରୀ ଡାକ୍ତରଖାନା", stats2: "ବିଭାଗ", stats3: "ମୁଫ୍ତ OPD", stats4: "ଜିଲ୍ଲା",
    featTitle: "Arogya.ai କ'ଣ କରେ?", featSub: "ସବୁ ଏକ ପ୍ଲାଟଫର୍ମରେ",
    howTitle: "3 ଧାପରେ ଚିକିତ୍ସା ଖୋଜନ୍ତୁ",
    ctaTitle: "ଆପଣଙ୍କ ଡାକ୍ତରଖାନା ଖୋଜିବାକୁ ପ୍ରସ୍ତୁତ?",
    ctaSub: "ଭାରତର 70% ଲୋକ ସରକାରୀ ଡାକ୍ତରଖାନା ଉପରେ ନିର୍ଭର କରନ୍ତି.",
    ctaBtn: "ଡାକ୍ତରଖାନା ଖୋଜ →", footerSub: "ସଠିକ ଚିକିତ୍ସା, ସଠିକ ଜାଗା, ସଠିକ ସମୟ",
    step1: "ଖୋଜ", step1d: "ଆପଣଙ୍କ ଲକ୍ଷଣ ବା ଜିଲ୍ଲା ଟାଇପ କରନ୍ତୁ",
    step2: "ଚୟନ କରନ୍ତୁ", step2d: "ନିକଟ ଡାକ୍ତରଖାନା ଚୟନ କରନ୍ତୁ",
    step3: "ଯାଆନ୍ତୁ", step3d: "ଦିଗ ପାଆନ୍ତୁ, OPD କାର୍ଡ ନିଅନ୍ତୁ",
  },
  ur: {
    tagline: "ہندوستان کا پہلا AI سرکاری ہسپتال نیویگیٹر",
    hero1: "صحیح علاج.", hero2: "صحیح جگہ.",
    subtitle: "اپنے ضلع کے سرکاری ہسپتال تلاش کریں — مفت شعبے، OPD اوقات، آیوشمان کوریج۔",
    placeholder: "علامت یا ہسپتال کا نام لکھیں...",
    allDistricts: "تمام اضلاع", search: "تلاش کریں →",
    stats1: "سرکاری ہسپتال", stats2: "شعبے", stats3: "مفت OPD", stats4: "اضلاع",
    featTitle: "Arogya.ai کیا کرتا ہے؟", featSub: "سب کچھ ایک پلیٹ فارم پر",
    howTitle: "3 مراحل میں علاج تلاش کریں",
    ctaTitle: "اپنا ہسپتال تلاش کرنے کے لیے تیار ہیں؟",
    ctaSub: "ہندوستان کے 70% لوگ سرکاری ہسپتالوں پر انحصار کرتے ہیں۔",
    ctaBtn: "ہسپتال تلاش کریں →", footerSub: "صحیح علاج، صحیح جگہ، صحیح وقت",
    step1: "تلاش", step1d: "اپنی علامت یا ضلع ٹائپ کریں",
    step2: "منتخب کریں", step2d: "قریبی ہسپتال منتخب کریں",
    step3: "جائیں", step3d: "سمت حاصل کریں، OPD کارڈ بنوائیں",
  },
}