export const INDIA_STATES_DISTRICTS = {
  "Andhra Pradesh": ["Visakhapatnam","Vijayawada","Guntur","Nellore","Kurnool","Tirupati","Rajahmundry","Kakinada","Anantapur","Kadapa","Srikakulam","Vizianagaram","Eluru","Ongole","Chittoor","West Godavari","East Godavari","Krishna","Prakasam","Sri Potti Sriramulu Nellore"],
  "Arunachal Pradesh": ["Itanagar","Naharlagun","Pasighat","Tawang","Ziro","Bomdila","Along","Tezu","Roing","Aalo"],
  "Assam": ["Guwahati","Dibrugarh","Jorhat","Silchar","Tezpur","Nagaon","Tinsukia","Bongaigaon","Dhubri","Goalpara","Karimganj","Hailakandi","Cachar","Kamrup","Darrang"],
  "Bihar": ["Patna","Gaya","Bhagalpur","Muzaffarpur","Darbhanga","Purnia","Arrah","Bihar Sharif","Begusarai","Katihar","Munger","Chhapra","Hajipur","Samastipur","Siwan","Aurangabad","Nalanda","Nawada","Jehanabad","Vaishali"],
  "Chhattisgarh": ["Raipur","Bhilai","Bilaspur","Durg","Korba","Rajnandgaon","Jagdalpur","Ambikapur","Raigarh","Dhamtari","Mahasamund","Kanker","Kondagaon","Sukma","Bastar"],
  "Goa": ["Panaji","Margao","Vasco da Gama","Mapusa","Ponda","North Goa","South Goa"],
  "Gujarat": ["Ahmedabad","Surat","Vadodara","Rajkot","Bhavnagar","Jamnagar","Gandhinagar","Junagadh","Anand","Navsari","Morbi","Mehsana","Surendranagar","Bharuch","Amreli","Botad","Dahod","Patan","Kheda","Sabarkantha"],
  "Haryana": ["Faridabad","Gurugram","Panipat","Ambala","Yamunanagar","Rohtak","Hisar","Karnal","Sonipat","Panchkula","Bhiwani","Sirsa","Rewari","Jhajjar","Fatehabad","Kurukshetra","Kaithal","Palwal","Nuh","Mahendragarh"],
  "Himachal Pradesh": ["Shimla","Mandi","Solan","Dharamsala","Baddi","Palampur","Nahan","Hamirpur","Una","Bilaspur","Chamba","Kullu","Kinnaur","Lahaul and Spiti","Sirmaur"],
  "Jharkhand": ["Ranchi","Jamshedpur","Dhanbad","Bokaro","Deoghar","Phusro","Hazaribagh","Giridih","Ramgarh","Medininagar","Chatra","Dumka","Pakur","Sahebganj","Jamtara"],
  "Karnataka": ["Bengaluru","Mysuru","Hubli","Mangaluru","Belagavi","Kalaburagi","Davanagere","Bellary","Tumkur","Shivamogga","Raichur","Bidar","Dharwad","Vijayapura","Hassan","Udupi","Mandya","Kodagu","Chikkamagaluru","Haveri"],
  "Kerala": ["Thiruvananthapuram","Kochi","Kozhikode","Thrissur","Kollam","Palakkad","Alappuzha","Kannur","Malappuram","Kasaragod","Kottayam","Idukki","Wayanad","Pathanamthitta","Ernakulam"],
  "Madhya Pradesh": ["Bhopal","Indore","Jabalpur","Gwalior","Ujjain","Sagar","Dewas","Satna","Ratlam","Rewa","Murwara","Singrauli","Burhanpur","Khandwa","Bhind","Chhindwara","Guna","Shivpuri","Vidisha","Chhatarpur"],
  "Maharashtra": ["Mumbai","Pune","Nagpur","Nashik","Aurangabad","Solapur","Kolhapur","Amravati","Nanded","Sangli","Malegaon","Jalgaon","Akola","Latur","Dhule","Ahmednagar","Chandrapur","Parbhani","Ichalkaranji","Jalna"],
  "Manipur": ["Imphal","Thoubal","Bishnupur","Churachandpur","Senapati","Tamenglong","Chandel","Ukhrul","Jiribam"],
  "Meghalaya": ["Shillong","Tura","Nongstoin","Williamnagar","Baghmara","Jowai","Nongpoh","Resubelpara","Ampati"],
  "Mizoram": ["Aizawl","Lunglei","Saiha","Champhai","Kolasib","Serchhip","Lawngtlai","Mamit"],
  "Nagaland": ["Kohima","Dimapur","Mokokchung","Tuensang","Wokha","Zunheboto","Phek","Kiphire","Longleng","Mon"],
  "Odisha": ["Bhubaneswar","Cuttack","Rourkela","Brahmapur","Sambalpur","Puri","Balasore","Baripada","Bhadrak","Jeypore","Barbil","Jharsuguda","Kendujhar","Angul","Dhenkanal"],
  "Punjab": ["Ludhiana","Amritsar","Jalandhar","Patiala","Bathinda","Hoshiarpur","Mohali","Pathankot","Moga","Firozpur","Batala","Gurdaspur","Ropar","Sangrur","Faridkot","Muktsar","Mansa","Barnala","Fazilka","Nawanshahr"],
  "Rajasthan": ["Jaipur","Jodhpur","Kota","Bikaner","Ajmer","Udaipur","Bhilwara","Alwar","Bharatpur","Sikar","Pali","Sri Ganganagar","Sirohi","Nagaur","Barmer","Jhunjhunu","Tonk","Dausa","Dholpur","Karauli"],
  "Sikkim": ["Gangtok","Namchi","Gyalshing","Mangan","Rangpo","Jorethang","Nayabazar","Singtam"],
  "Tamil Nadu": ["Chennai","Coimbatore","Madurai","Tiruchirappalli","Salem","Tirunelveli","Tiruppur","Ranipet","Nagercoil","Thanjavur","Vellore","Kancheepuram","Erode","Thoothukudi","Dindigul","Krishnagiri","Namakkal","Karur","Perambalur","Ariyalur"],
  "Telangana": ["Hyderabad","Warangal","Nizamabad","Karimnagar","Khammam","Ramagundam","Mahbubnagar","Nalgonda","Adilabad","Suryapet","Miryalaguda","Siddipet","Jagtial","Mancherial","Nirmal"],
  "Tripura": ["Agartala","Udaipur","Dharmanagar","Kailasahar","Belonia","Ambassa","Bishalgarh","Sonamura","Sabroom"],
  "Uttar Pradesh": ["Lucknow","Kanpur","Agra","Varanasi","Prayagraj","Meerut","Ghaziabad","Noida","Bareilly","Aligarh","Moradabad","Saharanpur","Gorakhpur","Faizabad","Jhansi","Mathura","Muzaffarnagar","Rampur","Firozabad","Hapur"],
  "Uttarakhand": ["Dehradun","Haridwar","Roorkee","Haldwani","Rudrapur","Kashipur","Rishikesh","Kotdwar","Ramnagar","Almora","Nainital","Pithoragarh","Bageshwar","Champawat","Chamoli"],
  "West Bengal": ["Kolkata","Howrah","Durgapur","Asansol","Siliguri","Bardhaman","Malda","Baharampur","Habra","Kharagpur","Shantipur","Dankuni","Dhulian","Ranaghat","Haldia","Raiganj","Krishnanagar","Nabadwip","Medinipur","Jalpaiguri"],
  "Delhi": ["New Delhi","Central Delhi","North Delhi","South Delhi","East Delhi","West Delhi","North East Delhi","North West Delhi","South East Delhi","South West Delhi","Shahdara","Dwarka"],
  "Jammu and Kashmir": ["Srinagar","Jammu","Baramulla","Anantnag","Sopore","Kathua","Udhampur","Rajouri","Punch","Doda","Ramban","Kishtwar","Shopian","Pulwama","Ganderbal"],
  "Ladakh": ["Leh","Kargil"],
}

export const STATE_LIST = Object.keys(INDIA_STATES_DISTRICTS).sort()